# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868d151b86aa7af1dfdc3285db349b186b2b6f7c1df7b0fdbff11b54492ee9104dc31c5b584e87899d3d0a08e99291e138783c6a77d885d84c189aeebbf09189

test:
  secret_key_base: 98c1b1af1b266b00ae7e53f4c74076585d28eb23ca9437ac75de168576f3619a519299aa2fc52b4514ad371bdd95a9cae773b51a04f1cf9d4fc71d895dff274d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
